#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dmarcguard"
name = "DMARCguard"
description.en = "Self-hosted DMARC report parser with dashboard and IMAP ingestion."
description.fr = "Parseur DMARC auto-heberge avec dashboard et ingestion IMAP."
version = "1.5.7~ynh1"
maintainers = ["rungeard"]

[upstream]
license = "Apache-2.0"
website = "https://dmarcguard.io/"
code = "https://github.com/dmarcguardhq/dmarcguard"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "120M"
ram.build = "50M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dmarcguard"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.imap_host]
    ask.en = "IMAP host (example: 127.0.0.1 or your mail domain)"
    ask.fr = "Hote IMAP (exemple : 127.0.0.1 ou votre domaine mail)"
    type = "string"

    [install.imap_port]
    ask.en = "IMAP port"
    ask.fr = "Port IMAP"
    type = "number"
    default = 993

    [install.imap_username]
    ask.en = "IMAP username"
    ask.fr = "Nom d'utilisateur IMAP"
    type = "string"

    [install.imap_password]
    ask.en = "IMAP password"
    ask.fr = "Mot de passe IMAP"
    type = "password"

    [install.imap_mailbox]
    ask.en = "IMAP mailbox"
    ask.fr = "Boite IMAP"
    type = "string"
    default = "INBOX"

    [install.imap_use_tls]
    ask.en = "Use TLS for IMAP"
    ask.fr = "Utiliser TLS pour IMAP"
    type = "boolean"
    default = true

[resources]
    [resources.sources.main]
    in_subdir = false
    rename = "parse-dmarc.tar.gz"

    amd64.url = "https://github.com/dmarcguardhq/dmarcguard/releases/download/v1.5.7/dmarcguard_linux_amd64.tar.gz"
    amd64.sha256 = "5c42bd918233550d529fc39294dcd07f831f10ed8acf9fb167105e8be8c19902"
    arm64.url = "https://github.com/dmarcguardhq/dmarcguard/releases/download/v1.5.7/dmarcguard_linux_arm64.tar.gz"
    arm64.sha256 = "1c138f4ff293bb4ca8098c1000be644172af96b39f9a89df0f72b939f2562811"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^(parse-dmarc|dmarcguard)_linux_amd64.tar.gz$"
    autoupdate.asset.arm64 = "^(parse-dmarc|dmarcguard)_linux_arm64.tar.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.data_dir]
