#!/bin/bash

source /usr/share/yunohost/helpers

ynh_script_progression "Setting up binary..."
ynh_setup_source --dest_dir="$install_dir"
chmod +x "$install_dir/parse-dmarc"

imap_use_tls_bool=false
if [ "$imap_use_tls" = "1" ] || [ "$imap_use_tls" = "true" ] || [ "$imap_use_tls" = "True" ]; then
    imap_use_tls_bool=true
fi
imap_use_tls="$imap_use_tls_bool"
ynh_app_setting_set --key=imap_host --value="$imap_host"
ynh_app_setting_set --key=imap_port --value="$imap_port"
ynh_app_setting_set --key=imap_username --value="$imap_username"
ynh_app_setting_set --key=imap_password --value="$imap_password"
ynh_app_setting_set --key=imap_mailbox --value="$imap_mailbox"
ynh_app_setting_set --key=imap_use_tls --value="$imap_use_tls_bool"

ynh_script_progression "Generating configuration..."
ynh_config_add --template="config.json" --destination="$install_dir/config.json"
chmod 600 "$install_dir/config.json"
chown "$app:$app" "$install_dir/config.json"

ynh_script_progression "Adding system configurations..."
ynh_config_add_nginx
ynh_config_add_systemd
ynh_config_add_logrotate
yunohost service add "$app" --description="DMARC parser and dashboard" --log="/var/log/$app/$app.log"
mkdir -p "/var/log/$app"
chown "$app:$app" "/var/log/$app"

ynh_script_progression "Starting service..."
ynh_systemctl --service="$app" --action=start --log_path="/var/log/$app/$app.log"
