#!/bin/bash

source /usr/share/yunohost/helpers

ynh_restore "$install_dir"
ynh_restore "$data_dir"
chown -R "$app:$app" "$install_dir" "$data_dir"

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

ynh_restore "/etc/logrotate.d/$app"
yunohost service add "$app" --description="DMARC parser and dashboard" --log="/var/log/$app/$app.log"

ynh_systemctl --service="$app" --action=start --log_path="/var/log/$app/$app.log"
ynh_systemctl --service=nginx --action=reload
